config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  resources :events, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attend.rb
class Attend < ApplicationRecord
    belongs_to :attended_event, class_name: "Event"
    belongs_to :attendee, class_name: "User"
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"
    has_many :attends, foreign_key: "attended_event_id"
    has_many :attendees, through: :attends, source: :attendee
    scope :future, -> { where("date >= ?", Date.today) }
    scope :past, -> { where("date < ?", Date.today) }

end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :events, foreign_key: "creator_id"
    has_many :attends, foreign_key: "attendee_id"
    has_many :attended_events, through: :attends, source: :attended_event

    def upcoming_events
        event = []
        self.events.each do |x|
            if !x.date.past?
                event.push(x)
            end
        end
        return event
    end

    def previous_events
        event = []
        self.events.each do |x|
            if x.date.past?
                event.push(x)
            end
        end
        return event
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    helper_method :logged_in?
    helper_method :upcoming_events

    def current_user
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    protected
  def authenticate_user!
    if logged_in?

    else
      redirect_to new_sessions_path
    end
  end

end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, :only => [:new]
    def index
        @events = Event.all
        @prev_events = Event.past
        @upcoming_events = Event.future
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.events.build(event_params)
        if @event.save
            redirect_to event_path(@event)
        else
            render :new
        end
    end

    def show
        @event = Event.find(params[:id])
        @attendees = @event.attendees.all
    end

    private
    def event_params
        params.require(:event).permit(:name,:date,:creator_id,:description,:attendees)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by_name(params[:session][:name])
        if user != nil
        session[:user_id] = user.id
        flash[:success] = "User logged in"
        redirect_to user_path(user)        
        else
            render :new      
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "Logged out"
        redirect_to new_sessions_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        @events = @user.events.all
        @upcoming_events = current_user.upcoming_events
        @prev_events = current_user.previous_events
    end


    private
    def user_params
        params.require(:user).permit(:name,:password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attends_helper.rb
module AttendsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<strong>Upcoming Events</strong>
<% @upcoming_events.each do |event| %>
<li>
<%= link_to event.name, event_path(event), class: 'post_title'%>
</li>
<% end %>
<strong>Previous Events</strong>
<% @prev_events.each do |event| %>
<li>
<%= link_to event.name, event_path(event), class: 'post_title'%>
</li>
<% end %>
<%= link_to "New Event", new_event_path, class: 'post_title'%>

app/views/events/new.html.erb
<%= form_for @event do |f| %>
<% if @event.errors.any? %>
<ul>
<% @event.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
</ul>
<% end %>
Name: <%= f.text_field :name, placeholder: "Name Here" %> <br/>
Date: <%= f.date_field :date %> <br/>
Description: <%= f.text_area :description, :cols => 30, :rows => 10 %> <br/>
<%= f.submit %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<br>
<%= @event.date %>
<br>
<%= @event.creator.name %>
<br>
<%= @event.description %>
<br>
<strong>Attendees</strong>
<br>
<% @attendees.each do |x| %>
<li>
<%= x.name %>
</li>
<% end %>

<%= link_to "<< Back to Events List", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%if flash[:notice] %>
  <div class="notification is-primary global-notification">
  <p class ="notice"><%= notice %></p>
  </div>
  <% end %>
  <% if flash[:alert] %>
  <div class="notification is-danger global-notification">
  <p class ="alert"><%= alert %></p>
  <% end %>

  <% if logged_in? %>
  <% if current_user.id != nil %>
  <p class="control">
    <%= link_to current_user.name, user_path(current_user.id), class: "button is-info"%>
  </p>
  <% else %>
  <%= current_user.name %>
  <% end %>
  <p>
  <%= link_to "Logout", sessions_path, method: :delete, class:"button is_info"%>
  </p>
  <% else %>
  <%= link_to "log in", new_sessions_path, class: "button is-info"%>
  <% end %>
  <%= link_to "make event", new_event_path, class: 'post_title'%>
  <br>
  <%= link_to "events", events_path, class: 'post_title'%>
  <br>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<ul>
<% @user.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
</ul>
<% end %>
Name: <%= f.text_field :name, placeholder: "Name Here" %> <br/>
Password: <%= f.password_field :password %> <br/>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<strong>User</strong>
<%= @user.name %>
<br>
<strong>Upcoming Events</strong>
<ul>
<% @upcoming_events.each do |event| %>
<li>
<%= link_to event.name, event_path(event), class: 'post_title'%>
</li>
<% end %>
</ul>
<strong>Previous Events</strong>
<ul>
<% @prev_events.each do |event| %>
<li>
<%= link_to event.name, event_path(event), class: 'post_title'%>
</li>
<% end %>
</ul>